name: look4me
description: Uma rede social de moda para mulheres decidirem seus looks.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_analytics: ^11.4.5

  url_launcher: ^6.3.1

  # State Management
  get: ^4.7.2
  provider: ^6.1.4

  # Adição para BLoC
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  get_it: ^8.0.3

  equatable: ^2.0.7

  # Local Storage
  shared_preferences: ^2.5.3

  # Connectivity
  connectivity_plus: ^6.1.3

  # Image
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1

  # Autenticação social
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # Validators
  email_validator: ^3.0.0

  # Performance & UI
  flutter_native_splash: ^2.4.6
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  lottie: ^3.3.1
  share_plus: ^10.1.4

  # Error Tracking
  sentry_flutter: ^8.14.1

  # Network
  dio: ^5.8.0+1

  # Permissions
  permission_handler: ^11.4.0

  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/  # Adicionei para animações Lottie

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
