// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC5SOTTiTWAPjXNebMDK01vAbmCmUds_k',
    appId: '1:380059027509:web:fa2a5aca33d32af030497c',
    messagingSenderId: '380059027509',
    projectId: 'look4me-app',
    authDomain: 'look4me-app.firebaseapp.com',
    storageBucket: 'look4me-app.firebasestorage.app',
    measurementId: 'G-99222BJ426',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNEX8dHFIxweKpUYzTJfBwGrLIzbFdfuc',
    appId: '1:380059027509:android:afc5dfe3a067239530497c',
    messagingSenderId: '380059027509',
    projectId: 'look4me-app',
    storageBucket: 'look4me-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0oFo6wAjcOEf-CO_eSPBPR6309z7SO4',
    appId: '1:380059027509:ios:594b595563bfffa030497c',
    messagingSenderId: '380059027509',
    projectId: 'look4me-app',
    storageBucket: 'look4me-app.firebasestorage.app',
    iosClientId: '380059027509-hpkl6k065us8sdnhhon3bd45u2hed62a.apps.googleusercontent.com',
    iosBundleId: 'com.selddon.look4me',
  );
}
